# -*- coding: utf-8 -*-
"""PabloCalfucura_PGY1121_009_D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xTSJ34YiaLTApu6KENWNmVbfrRkURg91
"""

# Prueba 3 Pablo Calfucura
personas = []

# Función para grabar los datos de la persona
def grabar_datos():
    nif = input("Ingrese el NIF: ")
    nombre = input("Ingrese el nombre: ")
    edad = int(input("Ingrese la edad: "))
    pertenencia_ue = input("Ingrese pertenencia a la UE (SI/NO): ")

    # Verificaciones respectivas
    if len(nif) != 11 or not nif[:8].isdigit() or not nif[8:].isalpha():
        print("El NIF ingresado es incorrecto.")
        return

    if len(nombre) < 8:
        print("El nombre debe tener al menos 8 caracteres.")
        return

    if edad < 0:
        print("La edad debe ser mayor o igual a 0.")
        return

    # Datos de la persona al arreglo
    persona = {"NIF": nif, "Nombre": nombre, "Edad": edad, "Pertenencia UE": pertenencia_ue}
    personas.append(persona)
    print("Datos grabados exitosamente.")

# Función para buscar persona mediante NIF
def buscar_persona():
    nif_buscar = input("Ingrese el NIF de la persona a buscar: ")

    for persona in personas:
        if persona["NIF"] == nif_buscar:
            print("Información de la persona:")
            print(f"NIF: {persona['NIF']}")
            print(f"Nombre: {persona['Nombre']}")
            print(f"Edad: {persona['Edad']}")
            print(f"Pertenencia a la UE: {persona['Pertenencia UE']}")
        else:
            print("No se encontró ninguna persona con el NIF ingresado.")

# Función para imprimir los certificados respectivos
import random
def imprimir_certificados():
    for persona in personas:
        print("Certificado del ciudadano:")
        print(f"NIF: {persona['NIF']}")
        print(f"Nombre: {persona['Nombre']}")
        print(f"Certificado de nacimiento: {random.randint(1000, 9999)}")
        print(f"Certificado de estado civil: {random.choice(['Soltero', 'Casado', 'Separado'])}")
        print(f"Certificado de/o no pertenencia a la UE: {random.randint(10000, 19999)}")
        print()

# Menú del Programa principal
while True:
    print("== Registro de ciudadanos Zona Euro España ==")
    print("1. Grabar datos")
    print("2. Buscar persona")
    print("3. Imprimir certificados")
    print("4. Salir")
    opcion = input("Ingrese una opción: ")

    if opcion == "1":
        grabar_datos()
    elif opcion == "2":
        buscar_persona()
    elif opcion == "3":
        imprimir_certificados()
    elif opcion == "4":
        break
    else:
        print("Opción inválida. Intente nuevamente.")

# Al salir mensaje final
print()
print()
print("************************")
print("++++++++++++++++++++++++")
print()
print("Gracias por su confianza")
print("Creado por: P. Calfucura")
print("++ Versión ---- 10.0  ++")
print()
print("++++++++++++++++++++++++")
print("************************")
print()
print()